name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Set SEPOLIA_RPC_URL Environment Variable
        run: echo "SEPOLIA_RPC_URL=https://rpc.sepolia.dev" >> $GITHUB_ENV
      
      - name: Run Forge tests
        run: |
          forge test --fork-url $SEPOLIA_RPC_URL
        id: test
